---
abstract: 'Bugzilla Bug Tracking System'
author:
  - 'Bugzilla Developers <developers@bugzilla.org>'
build_requires:
  ExtUtils::MakeMaker: '6.55'
  Pod::Coverage: '0'
  Test::More: '0'
  Test::WWW::Selenium: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.55'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bugzilla
no_index:
  directory:
    - t
    - inc
optional_features:
  auth_delegation:
    description: 'Auth Delegation'
    requires:
      LWP::UserAgent: '0'
  auth_ldap:
    description: 'LDAP Authentication'
    requires:
      Net::LDAP: '0'
  auth_radius:
    description: 'RADIUS Authentication'
    requires:
      Authen::Radius: '0'
  detect_charset:
    description: 'Automatic charset detection for text attachments'
    requires:
      Encode: '2.21'
      Encode::Detect: '0'
  documentation:
    description: Documentation
    requires:
      File::Copy::Recursive: '0'
      File::Which: '0'
  extension_bitly_optional:
    requires:
      Mozilla::CA: '0'
  extension_push_optional:
    requires:
      Net::SFTP: '0'
      XML::Simple: '0'
  features:
    description: 'Modules required to enable any feature'
    requires:
      CPAN::Meta::Prereqs: '2.132830'
      CPAN::Meta::Requirements: '2.121'
      Module::Metadata: '1.000019'
      Module::Runtime: '0'
  graphical_reports:
    description: 'Graphical Reports'
    requires:
      GD: '1.20'
      GD::Graph: '0'
      GD::Text: '0'
      Template::Plugin::GD::Image: '0'
  html_desc:
    description: 'More HTML in Product/Group Descriptions'
    requires:
      HTML::Parser: '3.67'
      HTML::Scrubber: '0'
  inbound_email:
    description: 'Inbound Email'
    requires:
      Email::MIME::Attachment::Stripper: '0'
      Email::Reply: '0'
      HTML::FormatText::WithLinks: '0.13'
  jobqueue:
    description: 'Mail Queueing'
    requires:
      Daemon::Generic: '0'
      TheSchwartz: '1.10'
  jsonrpc:
    description: 'JSON-RPC Interface'
    requires:
      JSON::RPC: '0'
      Test::Taint: '1.06'
  memcached:
    description: 'Memcached Support'
    requires:
      Cache::Memcached: '0.17'
  mfa:
    description: 'Multi-Factor Authentication'
    requires:
      Auth::GoogleAuth: '1.01'
      GD::Barcode::QRcode: '0'
  mod_perl:
    description: 'mod_perl support under Apache'
    requires:
      Apache2::SizeLimit: '0.96'
      mod_perl2: '1.999022'
  moving:
    description: 'Move Bugs Between Installations'
    requires:
      MIME::Parser: '5.406'
      XML::Twig: '0'
  mysql:
    description: 'MySQL database support'
    requires:
      DBD::mysql: '4.001'
  new_charts:
    description: 'New Charts'
    requires:
      Chart::Lines: v2.4.10
      GD: '1.20'
  old_charts:
    description: 'Old Charts'
    requires:
      Chart::Lines: v2.4.10
      GD: '1.20'
  oracle:
    description: 'Oracle database support'
    requires:
      DBD::Oracle: '1.19'
  patch_viewer:
    description: 'Patch Viewer'
    requires:
      PatchReader: v0.9.6
  pg:
    description: 'Postgres database support'
    requires:
      DBD::Pg: v2.19.3
  rest:
    description: 'REST Interface'
    requires:
      JSON::RPC: '0'
      Test::Taint: '1.06'
  smtp_auth:
    description: 'SMTP Authentication'
    requires:
      Authen::SASL: '0'
  sqlite:
    description: 'SQLite database support'
    requires:
      DBD::SQLite: '1.29'
  typesniffer:
    description: 'Sniff MIME type of attachments'
    requires:
      File::MimeInfo::Magic: '0'
      IO::Scalar: '0'
  updates:
    description: 'Automatic Update Notifications'
    requires:
      LWP::UserAgent: '0'
      XML::Twig: '0'
  xmlrpc:
    description: 'XML-RPC Interface'
    requires:
      SOAP::Lite: '0.712'
      Test::Taint: '1.06'
      XMLRPC::Lite: '0.712'
recommends:
  CPAN::Meta::Prereqs: '2.132830'
  CPAN::Meta::Requirements: '2.121'
  Module::Metadata: '1.000019'
  Module::Runtime: '0'
  Safe: '2.30'
requires:
  CGI: '3.51'
  Crypt::CBC: '0'
  Crypt::DES: '0'
  Crypt::DES_EDE3: '0'
  Crypt::OpenPGP: '1.02'
  Crypt::SMIME: '0'
  DBI: '1.614'
  Daemon::Generic: '0'
  Date::Format: '2.23'
  DateTime: '0.75'
  DateTime::TimeZone: '1.64'
  Digest::SHA: '0'
  Email::Address: '0'
  Email::MIME: '1.904'
  Email::Send: '1.911'
  File::MimeInfo::Magic: '0'
  File::Slurp: '9999.13'
  HTML::Tree: '0'
  IO::Compress::Gzip: '0'
  IO::Scalar: '0'
  JSON: '0'
  JSON::XS: '2.0'
  LWP: '6'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  List::MoreUtils: '0.32'
  Math::Random::ISAAC: v1.0.1
  Regexp::Common: '0'
  Sys::Syslog: '0'
  Template: '2.24'
  Text::Diff: '0'
  Tie::IxHash: '0'
  URI: '1.55'
  perl: '5.010001'
version: '4.2'
