name: BMO Perl Slim

on:
  workflow_dispatch

env:
  GAR_LOCATION: us
  GCP_PROJECT_ID: moz-fx-bugzilla-prod
  GAR_REPOSITORY: bugzilla-prod

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v2
    - name: Create directory for artifacts
      run: mkdir build_info
    - name: Generate timestamp
      run: echo "TIMESTAMP=$(date +%Y%m%d)" >> $GITHUB_ENV
    - name: Generate new cpanfile and cpanfile.snapshot
      run: docker build -t bmo-cpanfile -f Dockerfile.cpanfile .
    - name: Copy the new cpanfile and cpanfile.snapshot from image
      run: |
        docker run -v $(pwd):/app/result bmo-cpanfile cp cpanfile cpanfile.snapshot /app/result
        cp cpanfile cpanfile.snapshot build_info
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Info
        path: build_info
    - id: gcp-auth
      name: Google authentication
      uses: google-github-actions/auth@v2
      with:
        token_format: "access_token"
        service_account: artifact-writer@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}
    - name: Log in to the container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.gcp-auth.outputs.access_token }}
    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.bmo-slim
        tags: |
          ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/bmo-perl-slim:${{ env.TIMESTAMP }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
